### ISSUE TITLE
Component generator error with single quotes string

### ISSUE THREAD

**Issue by nicolas-brousse** [komposable/komponent#100]
On a project we use single quotes on js files. So our `frontend/components/index.js` has list of components with single quotes.  

The problem with when we generate a new component, the [`import_to_packs` method](https://github.com/komposable/komponent/blob/master/lib/generators/component/component_generator.rb#L37) seems to remove all components import and adding the new one.

```diff
- import "components/alert/alert";
- import "components/button/button";
- import "components/container/container";
- import "components/footer/footer";
- import "components/navigation/navigation";
- import "components/pagination/pagination";
+ import "components/test/test";
```

Not sure what could be done. May be using the `Komponent::Component.all` method a created on #95, could help us to do the import list directly by getting the list of present components.

**Comment by nicolas-brousse** [comment]
### How to reproduce the bug

```sh
$ rails new demo-app --webpack
$ cd demo-app
$ echo "gem 'komponent'" >> Gemfile
$ bundle
$ rails generate komponent:install
$ rails generate component container
$ rails generate component button
```

After what I got this inside `frontend/components/index.js`: 
```js
import "components/button/button";
import "components/container/container";
```

Ok, now I convert double to single quotes inside this file, then I generate a new component `rails generate component form`.

And `frontend/components/index.js` now contain:
```js
import "components/form/form";
```

**Comment by Spone** [comment]
Thanks for the instructions, it will help!

**Comment by nicolas-brousse** [comment]
Maybe the error is due to [`sort_lines_alphabetically!(path)`](https://github.com/komposable/komponent/blob/master/lib/generators/component/component_generator.rb#L171) and not `import_to_packs`.

**Comment by Spone** [comment]
I think you're right. Can you try modifying the regex from [this line](https://github.com/komposable/komponent/blob/master/lib/generators/component/component_generator.rb#L173)?

We would need `/^import ["'](.*)["'];$/` to support simple quotes.

**Comment by Spone** [comment]
I added a failing test case here: https://github.com/komposable/komponent/pull/101
and pushed this commit https://github.com/komposable/komponent/pull/101/commits/086be84f66e0483b97f63960095e49b26f557b98 to fix the issue.

But I'm not sure what behavior we want... Should we rewrite the whole index file with single or double quotes? How do we check what is the expected syntax for the current project?

**Comment by nicolas-brousse** [comment]
I think to start it's not really a problem to continue adding new component with double quotes. The main think is to not remove previous added components :)

**Comment by Spone** [comment]
Okay, let's merge this fix for now, and we may improve this later.
