### ISSUE TITLE
Having components present on bin/rails stats command

### ISSUE THREAD

**Issue by nicolas-brousse** [komposable/komponent#106]
I guess it could be nice to have stats who come from components into `bin/rails stats` command.  

https://github.com/rails/rails/blob/20c91119903f70eb19aed33fe78417789dbf070f/railties/lib/rails/tasks/statistics.rake

This is how `rspec-rails` do it.
https://github.com/rspec/rspec-rails/blob/e8054a1cd03044f725030fe8315952cf3799a395/lib/rspec/rails/tasks/rspec.rake#L8

May be we could have something similar to push components in Rails stats.

What do you think about?

**Comment by Spone** [comment]
Yes, it would be a nice-to-have feature!
