### ISSUE TITLE
content_for / yield is not working across components

### ISSUE THREAD

**Issue by stevschmid** [komposable/komponent#111]
Apparently this was adressed earlier (Issue https://github.com/komposable/komponent/issues/19, PR https://github.com/komposable/komponent/pull/21) but it seems the involving `view_flow` line
https://github.com/komposable/komponent/blob/dde02be9d08988e65c31b4c498e4f9440775a668/lib/komponent/komponent_helper.rb#L11-L15
didn't survive the refactoring into the `ComponentRenderer`
https://github.com/komposable/komponent/blob/74568b7346d08a4dc750525e107f350b3260c72d/lib/komponent/component_renderer.rb#L41-L46

**Comment by Spone** [comment]
Hi @stevschmid thanks for the report!

@florentferry can you confirm?

**Comment by Spone** [comment]
Hi @stevschmid thanks for your patience while we review your PR!

**Comment by Spone** [comment]
Thanks for your contribution @stevschmid!

**Comment by stevschmid** [comment]
Thanks for merging 👍
