### ISSUE TITLE
Add a generator for namespaced components

### ISSUE THREAD

**Issue by Spone** [komposable/komponent#12]
`rails g component admin/header` should create a `header` component in `frontent/components/admin/header`

Open to discussion:

- how should we name the Ruby module? `AdminHeaderComponent`? `Admin::HeaderComponent`?
- how should we name the CSS class? `admin_header`?
- how should we name the CSS and JS files? `admin_header.js|css`? just `header.js|css`?

**Comment by florentferry** [comment]
Except the CSS class which need to be changed due to possibles conflicts. We can name the CSS and JS files with short name `header.js|css`.
