### ISSUE TITLE
Readme says install will rename app/javascript to frontend, but no

### ISSUE THREAD

**Issue by pboling** [komposable/komponent#120]
According to the "Getting Started" section of the readme:
> This command will:
> • check that the dependencies (currently, webpacker) are installed
> • rename the app/javascript folder to frontend and modify webpacker config accordingly
> • create the frontend/components folder where you will put your component
> • create the frontend/components/index.js file that will list your components and import it in frontend/packs/application.js

The second step, renaming `app/javascript` to `frontend` did not happen, and as such the `modify webpacker config accordingly` has left things in a quite odd state.

It did *create* a `frontend` directory, but the old `app/javascript` directory is still present, and still has all the same stuff in it.

I am using latest versions of everything in a brand new Rails 5.2.1 app on Ruby 2.5.1

Output of install:
```
∴ rails generate komponent:install
Running via Spring preloader in process 45682
        gsub  config/webpacker.yml
      append  frontend/packs/application.js
         run  yarn add stimulus from "."
yarn add v1.9.4
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > webpack-dev-server@2.11.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
[4/4] 📃  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ stimulus@1.1.0
info All dependencies
└─ stimulus@1.1.0
warning No license field
✨  Done in 3.49s.
```

**Comment by Spone** [comment]
Hi @pboling, you're right, something is broken in the install generator.
The first step would be to fix the tests that failed to detect the issue. We started here: https://github.com/komposable/komponent/pull/98
Then once the tests break, we can start working on fixing the issue.

**Comment by colbyhub** [comment]
I see that #127 is open, is there any movement there? Would **love** to use this gem for projects, but it's definitely not super fun at the moment 😢

**Comment by Spone** [comment]
We're actively working on it, targetting the v3.0.0 release :)
Feel free to help!
