### ISSUE TITLE
Cut a new version?

### ISSUE THREAD

**Issue by bernardeli** [komposable/komponent#129]
Hi there,

Any plans to bump the minor version? I've been hit by the bug at PR #116. I can point my Gemfile to master in the meanwhile.

Thanks very much :)

**Comment by Spone** [comment]
Hi @bernardeli, I'm on it!

**Comment by Spone** [comment]
You can try [v3.0.0.beta1](https://github.com/komposable/komponent/releases/tag/v3.0.0.beta1)
