### ISSUE TITLE
Nested yields

### ISSUE THREAD

**Issue by aldhsu** [komposable/komponent#130]
I'm trying to write a Komponent with a method that renders another Komponent but something seems to be up with how the blocks are passed around.

I have built a repro case at https://github.com/aldhsu/komponent-nested-yields.

### Expected
Expect this:
```erb
<%# index.html.erb %>
<%= c "foo" do |foo| %>
  <%= foo.bar do %>
     Hello
  <% end %>
<% end %>
```

```erb
<%# _foo.html.erb %>
<div class="foo">
  <%= yield self %>
</div>
```

```rb
#foo_component.rb
module FooComponent
  extend ComponentHelper
  def bar(&block)
    component("bar", &block)
  end
end
```

```erb
<%# _bar.html.erb %>
<div class="bar">
  <%= yield %>
</div>
```

To output:
```html
<div class="foo">
  <div class="bar">
     Hello
  </div>
</div>
```

### Actual
```html
<div class="foo">
  Hello
  <div class="bar">
    Hello
  </div>
</div>
```

I'm not sure I entirely understand how the `capture` is supposed to work in this case so I don't know where to start looking. Basically I'm wrapping this behaviour:

```erb
<%= c "foo" do %>
  <%= c "bar" do %>
    Hello
  <% end %>
<% end %>
```

**Comment by Spone** [comment]
I think this issue is similar to #83, that has been handled with a workaround.
Since it's the second time this issue is raise, I think we should investigate further.
