### ISSUE TITLE
Komponent's view_renderer is leaking to Rails

### ISSUE THREAD

**Issue by robink** [komposable/komponent#144]
This commit seems to have introduce a bug in Rails 5.2 support (and certainly more versions) : 

https://github.com/komposable/komponent/commit/3aed17227e1a9d89586bc61905f304fa202b74b3#diff-d662fd06dc2cbab92ab384c4af54a041L12-R12

It happens that `@view_renderer ==  controller.view_context.view_renderer` is now `true`, which means komponent is leaking its view_renderer manipulation to Rails.

It prevents using both komponent rendering and standard Rails rendering.

**Comment by Spone** [comment]
@robink can you write a failing test case for this?

**Comment by robink** [comment]
I think I could indeed ! Just let me a couple a days to find some time to work on it

**Comment by robink** [comment]
Here you go ;-)

**Comment by Spone** [comment]
Thanks a lot @robink for contributing these tests. They seem to pass on the Rails 6 environment! We have to investigate how to fix this.

**Comment by robink** [comment]
Well I guess the fix is quite easy if you look at the commit that introduced the bug (cf start of this thread). I'm ok to do it if you want (next week).

**Comment by Spone** [comment]
Yes I guess we have to do `@view_renderer = @context.view_renderer.dup`

It would be great if you had the time to try this fix and add it to your PR!

**Comment by Spone** [comment]
Fixed in #146
