### ISSUE TITLE
Generate SCSS

### ISSUE THREAD

**Issue by sigmike** [komposable/komponent#23]
Shouldn't we generate a `.scss` file instead of a `.css`?

Or even better follow the configured preferred syntax (https://github.com/rails/sass-rails#options).

**Comment by Spone** [comment]
Personally I prefer to use CSS (with PostCSS / CSSnext), so IMHO it would be better to follow the Rails app configuration (as we do with the templating language).

**Comment by florentferry** [comment]
The same behavior than we already do with templating seems good. So preferred syntax at first, and `css` as fallback.
