### ISSUE TITLE
Dot prefix for locales

### ISSUE THREAD

**Issue by sigmike** [komposable/komponent#24]
With [this change](https://github.com/komposable/komponent/pull/18/files#diff-0d070a2ab0ce68ae1e2c8dcfe2f2f8adR2) the locale prefix becomes longer. It's good because it prevents conflicts but it makes the prefix even longer, so more painful to use.

I think we should :
1. either override `translate` (and `t`) to make keys starting with a dot look into the component locales (like [rails does](https://github.com/rails/rails/blob/master/actionpack/lib/abstract_controller/translation.rb#L13-L23))
2. or use the Rails "dot look up", i.e. generate a locale file with a default hierarchy including the full namespace, for example for an "admin/button" component: `<locale>.components.admin.button.admin_button` (to match the partial path).

I think 1. is better because the hierarchy is simpler and if you refactor your component by moving things into partial you don't have to change your keys.

**Comment by Spone** [comment]
:+1:  for option 1.

**Comment by andrzejsliwa** [comment]
can you provide examples how to use it?

**Comment by florentferry** [comment]
```
/ _button.html.slim

= t(".hello")

/ Instead of
/ = t("button_component.hello")
```

```
/ button.en.yml

de:
  button_component:
    hello: "Halo"
```
