### ISSUE TITLE
Style not being loaded

### ISSUE THREAD

**Issue by olimart** [komposable/komponent#37]
Salut,
très bonne idée ce gem.

J'ai suivi l'exemple du readme avec Stimulus mais il semble que le CSS dans le fichier `button.scss` ne soit pas chargé/compilé.

J'ai une application de test à disposition si besoin.

**Comment by florentferry** [comment]
Bonjour,

Merci pour l'intérêt que tu portes à Komponent.

J'ai essayé sur une application fraîchement créée, et je n'ai pas eu de problème. Je vois plusieurs raisons à ce problème :
- Le tag `stylesheet_pack_tag` n'est pas présent dans le layout de ton application.
- Dans ton composant, tu as un fichier de styles avec une extension `.scss` mais dans l'import, c'est un fichier avec une extension `.css`.

Si ce n'est pas ça malgré tout, tu peux soit poster içi le lien vers le code source de ton application de test, ou simplement les fichiers dans un [gist](https://gist.github.com/).
- frontend/components/index.js
- frontend/components/[ton_composant]/[ton_composant].js
- frontend/components/[ton_composant]/[ton_composant]_controller.js
- frontend/components/[ton_composant]/[ton_composant].css

**Comment by olimart** [comment]
Je n'avais pas réalisé que le stylesheet_pack_tag étais requis. Merci 👍
