### ISSUE TITLE
Configuration via initializer and components path

### ISSUE THREAD

**Issue by cseelus** [komposable/komponent#41]
Found this gem through the Evil Martians blog, nice idea to make a gem out of it.

How does the configuration via initializer work exactly, like so?

```ruby
Komponent.configure = {
  stimulus: true,
  locale: true
}
```

Also is it possible to change the default component path from `frontend` to say `app/frontend`?

**Comment by florentferry** [comment]
Hello @cseelus,

You can configure [Komponent generators](https://github.com/komposable/komponent#default-options-for-the-generators) by defining global options for both generators in an initializer:

```rb
config.generators do |g|
  g.komponent stimulus: true, locale: true # both are false by default
end
```

So next time, you generate a component, flags you're defined should be used.

Yes, it's possible to [change the default component directory](https://github.com/komposable/komponent#additional-paths) by overriding component paths in an initializer:

```rb
Rails.application.config.komponent.component_paths = [Rails.root.join("app/frontend")]
```

**Comment by florentferry** [comment]
Yeah, the setting does not affect generation. Like `component_paths` is used to resolved several endpoints, I don't think the setting should modify the location where components are generated. But an option on generator can be the right way to do that.  Actually they are no options for that, but we can add it.

This options need to be defined on generators: 
```rb
Rails.application.config.generators.komponent.locale = true
```

**Comment by cseelus** [comment]
Thanks again, thought I had tried `Rails.application.config.generators.komponent.locale`, but well … 😅

An option for the generator would be most welcome, as moving the generated files manually and deleting `/frontend` after each invocation defeats the purpose for anyone using a different folder somewhat.

**Comment by florentferry** [comment]
So I implement the feature you have requested, I let you check #43 to ensure it responds to your use case.
