### ISSUE TITLE
Add a method to return the list of components

### ISSUE THREAD

**Issue by Spone** [komposable/komponent#44]
If I want to create a styleguide / pattern library in my app, I'll need access to the list of available components.

I think Komponent should make a helper available to my views and/or add a class that I can use in my controllers.

**Comment by Spone** [comment]
@florentferry @sigmike As we discussed today, it may be a better idea to add this feature as part of another gem, which would be aimed a generating the styleguide / pattern library UI.

**Comment by florentferry** [comment]
:+1:
