### ISSUE TITLE
throw an exception when false or nil is passed into a component property

### ISSUE THREAD

**Issue by MittchoBaroco** [komposable/komponent#60]
# Expected Behavior
When passing a false or nil it should not crash

# Actual Behavior
throwing a NameError: `undefined local variable or method `options' for`

# Steps to Reproduce the Problem
passing a false or nil on any value of a component like this `<%= c "test", value: false %>`

# Context
I have a component that's taking in a boolean and display a check mark or a cross depending if it's a true or nil

# Specifications
Ruby version: 2.5.0
Rails version: 5.2.0.rc1
Komponent version: 1.1.1
Platform: Mac OS 10.13.2

**Comment by florentferry** [comment]
Hello @MittchoBaroco,

I think this issue is resolved by https://github.com/komposable/komponent/commit/0a2de8c38d2088ab1b983a91bb2df7ba468ad8a9 on `master` branch.

**Comment by MittchoBaroco** [comment]
let me try.

**Comment by MittchoBaroco** [comment]
Yes, thank you, to bad I wanted to try to solve it 😂
