### ISSUE TITLE
maybe we can provide rails app template for komponent?

### ISSUE THREAD

**Issue by andrzejsliwa** [komposable/komponent#74]
I made https://github.com/andrzejsliwa/rails_components_template, with my preferred setup, but maybe we can build more fancy generator (with "wizard" asking for different options). 

This will lower the entrance barier for komponent.io
What do you think about such idea?

**Comment by Spone** [comment]
Hi Andrzej,
we're happy that you chose to use Komponent by default in your Rails template.

I think that a Rails template usually reflects the preferences of its creator, so I'm not sure it makes sense for Komponent to provide such a template.

**Comment by florentferry** [comment]
Hello @andrzejsliwa,

 We have a custom template / engine / collection of generators to build our client projects, so we are not the target for such generic template. We have in mind to build and release an engine (https://github.com/komposable/komposable) which relies on `Komponent` for frontend and admin panel views.

Templates are pretty difficult to be shared, generic one contains a lot of code useless for most, specific one can't be easily customizable. You wanted to setup your projects in a minute, you made a template for your needs, we made ours. 

However, we're proud you decide to use Komponent in your default Rails template.
