### ISSUE TITLE
Component helper methods aren't included in remote renders

### ISSUE THREAD

**Issue by devonwalshe** [komposable/komponent#89]
A component that uses a helper method defined in its associated helper module returns a `NoMethodError`, when a controller action is called via ajax with a `remote: true` call. 

```ruby
# /components/foo_component/foo_component.html.haml 
=button_to foo_helper("foo"), foo_path, remote: true
```
```ruby
# /components/foo_component/foo_component.rb
Module FooComponent
    extend ComponentHelper
    def foo_helper(text)
       return text
    end
end
```
```ruby
# /app/controllers/foos_controller.rbs
...
def foo
    render partial: 'components/foo_component/foo_component'
end
```
If the helper method is included in the `app/helpers/foo.rb` it works just fine. 

App is on komponent 1.1.4 & Rails 5.1.

**Comment by Spone** [comment]
Hi @devonwalshe can you try with version [`2.0.0.pre.1`](https://rubygems.org/gems/komponent/versions/2.0.0.pre.1) of Komponent?

**Comment by florentferry** [comment]
Hello @devonwalshe,

Can you use `view_helper.component "foo_component"` in your controller instead of `render partial:` and let me know if you have always this issue.

**Comment by florentferry** [comment]
Hello @devonwalshe,

Nothing wrong here, you are using `render partial` from Rails, not `component` helper from Komponent. Only component helper load and inject component module into view context.

You can do what you want with:

```rb
def foo
  render html: helpers.component("foo")
end
```

**Comment by devonwalshe** [comment]
Cheers @florentferry, that indeed worked. Would agree it would be useful if this was documented. Many thanks!

**Comment by Spone** [comment]
I documented this in the cookbook: https://github.com/komposable/komponent/wiki#cookbook
