### ISSUE TITLE
how to import styles using an engine

### ISSUE THREAD

**Issue by Jbern16** [komposable/komponent#92]
Hello, 

I'm trying import styles from components that are hosted in an engine. I followed the directions for using `engine.js`, but receiving a `webpacker can't find engine.css in /Users/jonathanbernesser/native/kompsetup/public/packs/manifest.json` when doing the same instructions for `stylesheet pack_tag`.

If i create an `engine.scss`file next to the `engine.js` file, and import it into the `engine.js`, the error disappears, but no styles from the engine are compiled. Does anyone have an example setup to make this a reality?

Thanks!

**Comment by Spone** [comment]
Hi @Jbern16,

Usually, you will get the `webpacker can't find engine.css` error when your pack doesn't return any CSS. When you add some rules to your CSS file, the error will disappear.

Is your project accessible somewhere? I would need to see the whole file structure to help you debug it.

**Comment by Jbern16** [comment]
hey @Spone, I've created a public repo of the frontend dir structure that is in our engine. https://github.com/Jbern16/frontend. I've also included the webpacker.yml from our host app. These components were almost entirely generated using komponent generators

Thanks!

**Comment by Jbern16** [comment]
@Spone Hi! still having an issue with this. Its not just styles, but any packs can not be imported from my engine. I don't think it's as simple as including the `engine/frontend` in resolved paths. I've found this issue in webpack https://github.com/rails/webpacker/issues/21, that makes it seems that it is possible to compile packs from an engine. I am new to webpack so I may be conflating things...

Any help would be great!

**Comment by Spone** [comment]
Thanks for the feedback. I think we should follow this issue https://github.com/rails/webpacker/issues/348 to see if a recommended approach emerges.

We also did some experiments with NPM packages (basically installing your engine as a gem AND a NPM package) and it works, but it's not very straight-forward.

**Comment by Jbern16** [comment]
@Spone I ended up moving away from the copying and made my frontend folder in my engine its own NPM package and a git submodule. Yeah not super elegant but it works!
