### ISSUE TITLE
Return values from component with yield

### ISSUE THREAD

**Issue by nicolas-brousse** [komposable/komponent#93]
I'm trying to create a component to have a form container. And so use yield to pass the form helper to the view from the component.  
So I did the following.

```slim
# app/views/post/_form.html.slim

= c "form", model: @post, local: true do |f|
  div
    = f.label :name
    = f.text_field :name
```

```slim
# frontend/components/form/_form.html.slim

= form_with(model: @model, local: @local) do |form|
  .form(data-controller="form")
    = yield(form)
```

But I got this error : `ActionView::Template::Error (undefined method `label' for nil:NilClass)`.  

I tried to print the content of `form` or `f`. I have the form helper object inside the container, but in the view `f` is nil.

Does the block inside the view is rendered before the component?

**Comment by florentferry** [comment]
Hello @nicolas-brousse,

You can't do that now, but we can introduce this behavior.

You can override the component helper in your own project  by defining a custom component helper in your `app/helpers/pplication_helper.rb`:

```ruby
  def component(component_name, locals = {}, options = {}, &block)
    captured_block = proc { |args| capture(args, &block) } if block_given?
    Komponent::ComponentRenderer.new(
      controller,
    ).render(
      component_name,
      locals,
      options,
      &captured_block
    )
  end
  alias :c :component
```

**Comment by nicolas-brousse** [comment]
Thanks @florentferry.  
It works for me.

It could be nice to have it implemented inside Komponent 😃
